version: '3.8'

services:
  app:
    container_name: meli-challenge
    build: .
    command: streamlit run ğŸ _Home.py --server.port 7000
    #volumes:
    #  - .:/usr/src/app
    ports:
      - "7777:7000"